version: "3.7"
services:
  rasa:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
      - ./models:/app/models
      - ./credentials.yml:/app/credentials.yml
      - ./config.yml:/app/config.yml
      - ./endpoints.yml:/app/endpoints.yml
    command: basch -c "rm -rf models/* && rasa && rasa run --enable api --cors \"*\" --debug"
     ports:
      - 5005:5005
    networks:
      - all

  rasa-actions:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055
    networks:
      - all
  
  networks:
    all:
      driver: bridge
      driver_opts:
        com.docker.network.enable_ipv6: "true"